export type ListItem = {
    componentRiskRatingId: number,
    equipmentModel: string,
    component: string,
    componentType: string,
    maxRiskRank: string,
    revisedRank: string,
    overallRisk: string,
    failureTiming: string,
    systemImpact: string,
    opsImpact: string,
    supplyRisk: string,
    failureCost: string,
    comments: string,
    site: string,
    oemInterval: string,
    bumaAuTarget: string,
    componentWeight: string,
    startDate: string,
    endDate: string,
    isActive: number,
    createdOn: Date,
    createdBy: string,
    changedOn: Date,
    changedBy: string
}
