export type FilterData = {
    site: string,
    siteTo: string,
    equipmentModel: string,
    equipmentModelTo: string,
    component: string,
    componentTo: string,
    compartId: string,
    compartIdTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
