export type FilterData = {
    MenuName: string,
    PageName: string,
    Icon: string,
    MenuType: string,
    Level: string,
    Sequence: string,
    IsChild: boolean | null,
    ParentId: string,
    IsMenu: boolean | null,
    Section: string,
    MenuNameTo: string,
    PageNameTo: string,
    IconTo: string,
    MenuTypeTo: string,
    LevelTo: string,
    SequenceTo: string,
    ParentIdTo: string,
    SectionTo: string,
    Page: number,
    PageSize: number,
    Order: string,
    ver: string
}
