export type ListItem = {
    MdId: number,
    MenuName: string,
    PageName: string,
    // Icon: string | null,
    MenuType: string,
    Level: number,
    Sequence: number,
    IsChild: boolean,
    ParentId: number,
    IsMenu: boolean,
    Section: string,
    IsActive: boolean,
    IsDelete: boolean,
    CreatedOn: Date,
    CreatedBy: string,
    ChangedOn: Date,
    ChangedBy: string,
}
