export type FilterData = {
    type: string,
    typeTo: string,
    sequential: string,
    sequentialTo: string,
    operator: string,
    operatorTo: string,
    valueMin: string,
    valueMinTo: string,
    valueMax: string,
    valueMaxTo: string,
    uom: string,
    uomTo: string,
    category: string,
    categoryTo: string,
    categoryDesc: string,
    categoryDescTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
