export type FilterData = {
    equipment: string,
    equipmentTo : string,
    characteristicType : string,
    characteristicTypeTo : string,
    characteristicValue : string,
    characteristicValueTo : string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
