export type FilterData = {
    site: string,
    siteTo: string,
    equipmentModel: string,
    equipmentModelTo: string,
    cbmGroup: string,
    cbmGroupTo: string,
    componentStatusId: string,
    componentStatusIdTo: string,
    objectType: string,
    objectTypeTo: string,
    group: string,
    groupTo: string,
    rating: string,
    ratingTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
