export type FilterData = {
    UnitNumber: string,
    SmuDue: string,
    WorkOrder: string,
    PsType: string,
    DateService: string,
    LastWorkOrder: string,
    LastPsType: string,
    LastDateService: string,
    StartDate: string,
    EndDate: string,
    UnitNumberTo: string,
    SmuDueTo: string,
    WorkOrderTo: string,
    PsTypeTo: string,
    DateServiceTo: string,
    LastWorkOrderTo: string,
    LastPsTypeTo: string,
    LastDateServiceTo: string,
    StartDateTo: string,
    EndDateTo: string,
    Status: string,
    Page: number,
    PageSize: number,
    Order: string,
    ver: string
}
