export type FilterData = {
    interventionStatus: string,
    interventionStatusTo: string,
    interventionStatusDesc: string,
    interventionStatusDescTo: string,
    followUpPriority: string,
    followUpPriorityTo: string,
    followUpPriorityUom: string,
    followUpPriorityUomTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
