export type BulkItem = {
    componentStatusId: number,
    component: string,
    componentDesc: string,
    sensorData: string,
    oilDataS1: string,
    oilDataS2: string,
    filterCutS1: string,
    filterCutS2: string,
    magPlug: string,
    ironFormsCbm: string,
    componentStatus: string,
    startDate: string,
    endDate: string,
}
