export type FilterData = {
    component: string,
    componentTo: string,
    sensorData: string,
    sensorDataTo: string,
    oilDataS1: string,
    oilDataS1To: string,
    oilDataS2: string,
    oilDataS2To: string,
    filterCutS1: string,
    filterCutS1To: string,
    filterCutS2: string,
    filterCutS2To: string,
    magPlug: string,
    magPlugTo: string,
    ironFormsCbm: string,
    ironFormsCbmTo: string,
    componentStatus: string,
    componentStatusTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
