import { Audit } from './Audit'

export interface IBaseDefectHeader {
    workorder: string,
    form: string,
    serviceSheetDetailId: string,
    interventionId: string,
    interventionHeaderId: string,
    category: string,
    taskId: string,
    taskNo: string,
    taskDesc: string,
    defectWorkorder: string,
    formDefect: string,
    defectType: string,
    cbmMeasurement: string,
    cbmUom: string,
    cbmImageKey: string,
    cbmImageProp: string,
    isCbmAdjusment: string,
    taskValue: string,
    repairedStatus: string,
    cbmNAStatus: string,
    supervisor: Audit,
    status: string,
    defectStatus: string,
    isActive?: string,
    plannerStatus: string,
    declineReason: string,
    declineBy: Audit,
    declineDate: string,
    approvedBy: Audit,
    approvedDate: string,
    createdBy: Audit,
    createdDate: string,
    updatedBy: Audit,
    updatedDate: string,
    id?: string // for generic
    correctedValue?: string,
    correctedMeasurement?: string,
    correctedUom?: string
}
