export type FilterData = {
    ComponentId: string
    CbmGroup: string,
    CbmArea: string,
    CbmParameterId: string,
    ModelId: string
    PsTypeId: string
    TaskNumber: string,
    DetailNumber: string,
    CbmParameter: string,
    Parameter: string
    TypeParameterId: string
    MinValue: string,
    MaxValue: string,
    Uom: string,
    StatusConverter: string,
    StatusDescriptionConverter: string,
    Status: string,
    StatusDescription: string,
    StartDate: string,
    EndDate: string,
    ComponentIdTo: string
    CbmGroupTo: string,
    CbmAreaTo: string,
    CbmParameterIdTo: string,
    ModelIdTo: string
    PsTypeIdTo: string
    TaskNumberTo: string,
    DetailNumberTo: string,
    CbmParameterTo: string,
    ParameterTo: string
    TypeParameterIdTo: string
    MinValueTo: string,
    MaxValueTo: string,
    UomTo: string,
    StatusConverterTo: string,
    StatusDescriptionConverterTo: string,
    StatusTo: string,
    StatusDescriptionTo: string,
    StartDateTo: string,
    EndDateTo: string,
    Page: number,
    PageSize: number,
    Order: string,
    ver: string
}
