export type ListItem = {
    mdParameterEhmsId: number,
    componentId: string,
    cbmGroup: string,
    cbmArea: string,
    cbmParameterId: string,
    modelId: string,
    psTypeId: string,
    taskNumber: string,
    detailNumber: string,
    cbmParameter: string,
    parameter: string,
    minValue: string,
    maxValue: string,
    uom: string,
    statusConverter: string,
    statusDescriptionConverter: string,
    status: string,
    statusDescription: string,
    validFrom: string,
    validTo: string,
    typeParameterId: string,
    createdOn: string,
    createdBy: string,
    changedOn: string,
    changedBy: string,
    isActive: boolean
}
