export type LookupItem = {
    cbmArea: string[]
    cbmGroup: string[]
    cbmParameter: string[]
    cbmParameterId: string[]
    componentId: string[]
    detailNumber: string[]
    maxValue: string[]
    minValue: string[]
    modelId: string[]
    parameter: string[]
    psTypeId: string[]
    status: string[]
    statusConverter: string[]
    statusDescription: string[]
    statusDescriptionConverter: string[]
    taskNumber: string[]
    uom: string[]
};
