export type ListItem = {
  equipmentAssignmentId: number,
  equipment: string,
  objectType: string,
  plannerGroup: string,
  costCenter: string,
  wbsElement: string,
  level: string,
  equipmentType: string,
  equipmentGroup: string,
  equipmentModel: string,
  equipmentStatus: string,
  site: string,
  planningPlant: string,
  maintenancePlant: string,
  maintenanceWorkCenter: string,
  startDate: string,
  endDate: string,
  createdBy: string,
  createdOn: Date,
  changedBy: string,
  changedOn: Date,
  isActive: boolean
}
