export type ValidatedItem = {
    equipment: string,
    objectType: string,
    plannerGroup: string,
    costCenter: string,
    wbsElement: string,
    level: string,
    equipmentType: string,
    equipmentGroup: string,
    equipmentModel: string,
    equipmentStatus: string,
    site: string,
    planningPlant: string,
    maintenancePlant: string,
    maintenanceWorkCenter: string,
    startDate: Date,
    endDate: Date,
    isValid: boolean,
    validationReason: string
}
