export type FilterData = {
    cluster: string,
    clusterTo: string,
    sampleCount : string,
    sampleCountTo : string,
    sampleWeight: string,
    sampleWeightTo: string,
    cautionLimit: string,
    cautionLimitTo: string,
    criticalLimit: string,
    criticalLimitTo: string,
    summaryWeight: string,
    summaryWeightTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
export type FilterDataSpecific = {
    cbmGroup: string,
    cbmGroupTo: string,
    component: string,
    componentTo: string,
    parameter: string,
    parameterTo: string,
    cluster: string,
    clusterTo: string,
    sampleCount : string,
    sampleCountTo : string,
    sampleWeight: string,
    sampleWeightTo: string,
    cautionLimit: string,
    cautionLimitTo: string,
    criticalLimit: string,
    criticalLimitTo: string,
    summaryWeight: string,
    summaryWeightTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
