export type FilterData = {
    equipmentModel: string,
    equipmentModelTo: string,
    component: string,
    componentTo: string,
    element: string,
    elementTo: string,
    rating: string,
    ratingTo: string,
    operatorMin: string,
    operatorMinTo: string,
    valueMin: string,
    valueMinTo: string,
    operatorMax: string,
    operatorMaxTo: string,
    valueMax: string,
    valueMaxTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
