/* eslint-disable @typescript-eslint/no-explicit-any */
export type InterventionCheckItem = {
    interventionHeaderId: number,
    interventionHeaderSourceId: number,
    interventionDetailId: number,
    interventionDetailSourceId: number,
    sequence: any,
    subTask: string | null,
    recAction: string,
    executed: boolean,
    actualInterventionDate: string,
    interventionStatus: string,
    condition: string | null,
    detailedInformation: string | null,
    taskKey: string,
    isActive: boolean,
    isDeleted: boolean,
    value: number,
    uom: number,
    rating: string,
    spvStatus: string,
    plannerStatus: string,
    declineReason: string,
    psType: string,
    interventionIdCosmos: string,
    images:string[],
    isMandatory: boolean,
    keyPbi: string
}
