export type ListItem = {
    unitNumber: string,
    smuDue: string,
    workOrder: string,
    psType: string,
    dateService: string,
    model: string,
    lastPsType: string,
    lastDateService: string,
    lastWorkOrder: string,
    taskNumberDetail: string,
    locationId: string,
    lastTaskNumberDetail: string,
    lastLocationId: string,
    startDate: string,
    endDate: string,
    isActive: boolean,
    createdOn: string,
    createdBy: string,
    changedOn: string,
    changedBy: string,
}
