export type FilterData = {
    equipmentModel: string,
    equipmentModelTo: string,
    objectType: string,
    objectTypeTo: string,
    cbmGroup: string,
    cbmGroupTo: string,
    area: string,
    areaTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
