export type FilterData = {
    EquipmentModel : string,
    EquipmentModelTo : string,
    PsType : string,
    PsTypeTo : string,
    Component : string,
    ComponentTo :string,
    RecomLubricant : string,
    RecomLubricantTo : string,
    Value : string,
    ValueTo : string,
    Uom : string,
    UomTo : string,
    TaskNo : string,
    TaskNoTo : string,
    StartDate : string,
    StartDateTo : string,
    EndDate : string,
    EndDateTo : string,
    Page: number,
    PageSize: number,
    Order: string,
    ver: string
}
