export type FilterData = {
    type: string,
    typeTo: string,
    typeDescription: string,
    typeDescriptionTo: string,
    parameter: string,
    parameterTo: string,
    parameterDescription: string,
    parameterDescriptionTo: string,
    parameterGroup: string,
    parameterGroupTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
