export type FilterData = {
    componentCode: string,
    componentCodeTo: string,
    equipmentModel: string,
    equipmentModelTo: string,
    modifierCode: string,
    modifierCodeTo: string,
    taskType: string,
    taskTypeTo: string,
    strategyTaskDesc: string,
    strategyTaskDescTo: string,
    oemInterval: string,
    oemIntervalTo: string,
    percentageOfOem: string,
    percentageOfOemTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
