export type FilterData = {
    maxRiskRank: string,
    maxRiskRankTo: string,
    revisedRisk: string,
    revisedRiskTo: string,
    overallRisk: string,
    overallRiskTo: string,
    failureTiming: string,
    failureTimingTo: string,
    systemImpact: string,
    systemImpactTo: string,
    opsImpact: string,
    opsImpactTo: string,
    supplyRisk: string,
    supplyRiskTo: string,
    failureCost: string,
    failureCostTo: string,
    comments: string,
    commentsTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
