export type FilterData = {
    cbmType: string,
    cbmTypeTo: string,
    equipmentModel : string,
    equipmentModelTo: string,
    component: string,
    componentTo: string,
    valueThreshold: string,
    valueThresholdTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
