export type FilterData = {
    site: string,
    siteTo: string,
    equipmentModel: string,
    equipmentModelTo: string,
    weight: string,
    weightTo: string,
    whPerday: string,
    whPerdayTo: string,
    fuelBurn: string,
    fuelBurnTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
