export type FilterData = {
    site: string,
    siteTo: string,
    equipmentModel: string,
    equipmentModelTo: string,
    equipmentNumber: string,
    equipmentNumberTo: string,
    component: string,
    componentTo: string,
    smu: string,
    smuTo: string,
    counterReading: string,
    counterReadingTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
