import { Employee } from "./Employee"

export type DefectHeader = {
    workorder: string,
    form: string,
    serviceSheetDetailId: string,
    category: string,
    taskId: string,
    taskNo: string,
    taskDesc: string,
    defectWorkorder: string,
    formDefect: string,
    defectType: string,
    cbmMeasurement: string,
    cbmUom: string,
    cbmImageKey: string,
    cbmImageProp: string,
    isCbmAdjusment: string,
    taskValue: string,
    repairedStatus: string,
    cbmNAStatus: string,
    supervisor: Employee,
    status: string,
    defectStatus: string,
    isActive?: string,
    defectHeaderId?: string,
    defectDetailId?: string,
    cbmRatingType?: string,
    pic?: string,
    role?: string,
    declineReason?: string,
    approveReason?: string,
    action?: string
}
