export type FilterData = {
    site: string,
    siteTo: string,
    equipmentModel:string,
    equipmentModelTo:string,
    equipmentNumber: string,
    equipmentNumberTo: string,
    component: string,
    componentTo: string,
    hoCycleTarget: string,
    hoCycleTargetTo: string,
    siteCycleTarget: string,
    siteCycleTargetTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
