export type FilterData = {
    EquipmentModel: string,
    PsType: string,
    TaskNo: string,
    TaskCrackCode: string,
    LocationId: string,
    Uom: string,
    StartDate: string,
    EndDate: string,
    EquipmentModelTo: string,
    PsTypeTo: string,
    TaskNoTo: string,
    TaskCrackCodeTo: string,
    LocationIdTo: string,
    UomTo: string,
    StartDateTo: string,
    EndDateTo: string,
    Page: number,
    PageSize: number,
    Order: string,
    ver: string
}
