export type FilterData = {
    idOemInterval: string,
    idOemIntervalTo: string,
    interval: string,
    intervalTo: string,
    value: string,
    valueTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
