export type DraftItem = {
  cbmParameterDraftId: number,
  taskKey: string,
  equipmentModel: string,
  serviceSize: string,
  taskDescription: string,
  uom: string,
  typeParameter: string,
  status: string,
  rating: string,
  minValue: string,
  maxValue: string,
  component: string,
  cbmGroup: string,
  taskNo: string,
  taskNoDetail: string,
  modifiedOn: string,
  modifiedBy: string,
  validationReason: string,
};
