/* eslint-disable @typescript-eslint/no-explicit-any */
export type FilterData = {
    cbmType:string,
    cbmTypeTo:string,
    equipmentModel: string,
    equipmentModelTo: string,
    component: string,
    componentTo: string,
    parameterTo: string,
    parameterToTo: string,
    interventionCode: string,
    interventionCodeTo: string,
    recAction: string,
    recActionTo: string,
    sampleStatus: string,
    sampleStatusTo: string,
    sequence: string,
    sequenceTo: string,
    subTask: string,
    subTaskTo: string,
    isUom: string,
    isUomTo: string,
    uom: string,
    uomTo: string,
    referenceDocument: string,
    referenceDocumentTo: string,
    isAutoFill: string,
    isAutoFillTo: string,
    psType: string,
    psTypeTo: string,
    taskGroupKey: string,
    taskGroupKeyTo: string,
    taskKey: string,
    taskKeyTo: string,
    typeTask: string,
    typeTaskTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
