export type ListItem = {
    recommendedActionId: number,
    cbmType:string,
    equipmentModel: string,
    component: string,
    parameterTo: string,
    interventionCode: string,
    recAction: string,
    sampleStatus: string,
    sampleStatusId: string,
    sequence: string,
    subTask: string,
    isUom: boolean,
    isAutoFill: boolean,
    uom: string,
    referenceDocument: string,
    psType: string,
    taskGroupKey: string,
    taskKey: string,
    typeTask: string,
    startDate: string,
    endDate: string,
    isActive: number,
    createdOn: Date,
    createdBy: string,
    changedOn: Date,
    changedBy: string
}
