export type UpsertItem = {
    recommendedActionId: number,
    cbmType:string,
    equipmentModel: string,
    component: string,
    parameterTo: string,
    interventionCode: string,
    recAction: string,
    sampleStatus: string,
    sampleStatusId: string,
    sequence: string,
    subTask: string,
    isUom: boolean,
    isAutoFill: boolean,
    psType: string,
    taskGroupKey: string,
    taskKey: string,
    typeTask: string,
    uom: string,
    referenceDocument: string,
    startDate: string,
    endDate: string,
}
