export type FilterData = {
    site: string,
    siteTo: string,
    equipmentModel: string,
    equipmentModelTo: string,
    objectType: string,
    objectTypeTo: string,
    codeGroup: string,
    codeGroupTo: string,
    damageCategory: string,
    damageCategoryTo: string,
    damage: string,
    damageTo: string,
    startDate: string,
    startDateTo: string,
    endDate: string,
    endDateTo: string,
    page: number,
    pageSize: number,
    order: string,
    ver: string,
}
