export type FilterData = {
    Model: string,
    ModelTo: string,
    PsType: string,
    PsTypeTo: string,
    TaskNumberDetailParent: string,
    TaskNumberDetailParentTo: string,
    LocationIdParent: string,
    LocationIdParentTo: string,
    TaskNumberDetailChild: string,
    TaskNumberDetailChildTo: string,
    LocationIdChild: string,
    LocationIdChildTo: string,
    StartDate: string,
    StartDateTo: string,
    EndDate: string,
    EndDateTo: string,
    Page: number,
    PageSize: number,
    Order: string,
    ver: string
}
